[package]
name = "pe-346"
version = "0.1.0"
authors = ["gh1dra <ced361@nyu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
